# Cloud Build pipeline for main-api Cloud Run-deploy.
# Source er repo-rot, så vi må bruke `dir: services/main-api` for build.

steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    dir: services/main-api
    args:
      - build
      - --tag=europe-north1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/main-api-staging:${SHORT_SHA}
      - --tag=europe-north1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/main-api-staging:latest
      - .

  - id: push-sha
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-north1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/main-api-staging:${SHORT_SHA}

  - id: push-latest
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-north1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/main-api-staging:latest

  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - main-api-staging
      - --image=europe-north1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/main-api-staging:${SHORT_SHA}
      - --region=europe-north1
      - --project=${PROJECT_ID}
      - --quiet

options:
  logging: CLOUD_LOGGING_ONLY
